### ISSUE TITLE
cmd/apmtool: add a command to send a mixed OTLP and intake-v2 trace

### ISSUE THREAD

**Issue by axw** [elastic/apm-tools#1]
Add a command to send a distributed trace using a mix of opentelemetry-go (OTLP/gRPC) and apm-agent-go (intake-v2).

The trace must include the following:
 - at least one transaction
 - at least one span (with `service.target.*` to trigger `service_destination` metrics aggregation)
 - at least one trace-correlated error
 - at least one trace-correlated log

The command should also support:
 - a configurable sample rate to report to APM Server, to control extrapolation
 - flags for waiting for events to be indexed, using the same functionality underlying https://github.com/elastic/apm-tools/issues/2

The search performed in the final step of waiting for events to be indexed should include two [runtime fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#run-search-runtime-fields) (names TBD):
 - `event.ingested - @timestamp`
 - `event.ingested - event.received`
```[tasklist]
### Tasks
- [x] Use apm-agent-go to create a trace
- [x] Use opentelemetry-go to create a trace that shares the same traceID
```

**Comment by kyungeunni** [comment]
I didn't close this earlier because we haven't addressed this:
>flags for waiting for events to be indexed, using the same functionality underlying https://github.com/elastic/apm-tools/issues/2
The search performed in the final step of waiting for events to be indexed should include two [runtime fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#run-search-runtime-fields) (names TBD):

> event.ingested - @timestamp
> event.ingested - event.received

Is this ok to skip as it's done in the smoke-test in managed service??

**Comment by marclop** [comment]
@kyungeunni could you open an issue for the leftovers in this task? We can always add them later.
