### ISSUE TITLE
cmd/apmtool: Add `insecure` flag to skip TLS validation

### ISSUE THREAD

**Issue by marclop** [elastic/apm-tools#13]
## Description

In order to be able to use apmtool against an Elasticsearch that uses a self signed certificate, we should add an `insecure` flag

**Comment by endorama** [comment]
Is also part of this task to configure TLS for clients based on the flag value?

I quickly reviewed the code and my understanding is that TLS should be configured for clients used by `espoll` command and `apmclient` package.

**Comment by axw** [comment]
@endorama yes I think it would make sense for the flag to configure TLS all clients. It would probably make sense to move the `-insecure` flag from the [tracegen subcommand][1] to the [top level][2], and make it a persistent flag.

[1]: https://github.com/elastic/apm-tools/blob/75a6b76ed870a2eadfc0e96682df72b48f28a15e/cmd/apmtool/tracegen.go#L89-L93
[2]: https://github.com/elastic/apm-tools/blob/75a6b76ed870a2eadfc0e96682df72b48f28a15e/cmd/apmtool/main.go#L31
