### ISSUE TITLE
apmtool agent-env --api-key-expiration fails with type error

### ISSUE THREAD

**Issue by endorama** [elastic/apm-tools#24]
When using `--api-key-expiration` the `agent-env` command fails with an error from ES:

```
$ ELASTICSEARCH_URL=https://local.es.127.0.0.1.ip.es.io:8443 ELASTIC_APM_SERVER_URL=https://local.apm.127.0.0.1.ip.es.io:8443 go run cmd/apmtool -v agent-env --api-key-expiration 60s --insecure
error getting APM cloud input: expected 1 policy, got 0
Creating agent API Key...
2023/08/28 18:50:05 failed to obtain agent credentials: error creating agent API Key: status: 400, failed: [x_content_parse_exception], reason: [1:15] [api_key_request] expiration doesn't support values of type: VALUE_NUMBER
error getting APM cloud input: expected 1 policy, got 0
exit status 1
```

My understanding is that the request is rejected by ES due to `expiration` being a number.

From the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) expiration should be a string (es `1s`, like Golang `time.Duration`):
> **expiration**
> (Optional, string) Expiration time for the API key. By default, API keys never expire. 

It seems the client is passing an int, which is rejected. The request is marshaled by the ES go library `github.com/elastic/go-elasticsearch/v8`.

Opening this here to signal that the flag is at the moment unusable.

**Comment by axw** [comment]
go-elasticsearch expects a formatted duration string, not a time.Duration: https://github.com/elastic/go-elasticsearch/blob/624594e8d72aad852711469005959dbc8238f2f2/typedapi/types/duration.go#L23-L28

Should be fixed by https://github.com/elastic/apm-tools/pull/26.
